remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/just-the-docs.png"

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"